//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDSProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealthITDBContainer1 : DbContext
    {
        public HealthITDBContainer1()
            : base("name=HealthITDBContainer1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Doctor> DoctorSet { get; set; }
        public virtual DbSet<Appointment> AppointmentSet { get; set; }
        public virtual DbSet<ConsultationDet> ConsultationDetSet { get; set; }
    }
}
