//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDSProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class HelpDesk : User
    {
        public string Name { get; set; }
        public int CheckIn { get; set; }
        public int CheckOut { get; set; }
    }
}
